-- MySQL Script generated by MySQL Workbench
-- Tue Oct 12 23:15:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Taxi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Taxi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Taxi` DEFAULT CHARACTER SET utf8 ;
USE `Taxi` ;

-- -----------------------------------------------------
-- Table `Taxi`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Taxi`.`Usuario` (
  `idUsuario` INT NOT NULL auto_increment,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `tlf` VARCHAR(45) NOT NULL,
  `tarjeta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Taxi`.`Taxi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Taxi`.`Taxi` (
  `idTaxi` INT NOT NULL auto_increment,
  `estado` VARCHAR(45) NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  `destino` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTaxi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Taxi`.`Viaje_Taxi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Taxi`.`Viaje_Taxi` (
  `idViaje_Taxi` INT NOT NULL auto_increment,
  `Usuario_idUsuario` INT NOT NULL,
  `Taxi_idTaxi` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `origen` VARCHAR(45) NOT NULL,
  `destino` VARCHAR(45) NOT NULL,
  `coste` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idViaje_Taxi`, `Usuario_idUsuario`, `Taxi_idTaxi`),
  INDEX `fk_Viaje_Taxi_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Viaje_Taxi_Taxi1_idx` (`Taxi_idTaxi` ASC) VISIBLE,
  CONSTRAINT `fk_Viaje_Taxi_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Taxi`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viaje_Taxi_Taxi1`
    FOREIGN KEY (`Taxi_idTaxi`)
    REFERENCES `Taxi`.`Taxi` (`idTaxi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Taxi`.`Sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Taxi`.`Sesion` (
  `idSesion` INT NOT NULL auto_increment,
  `Usuario_idUsuario` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  PRIMARY KEY (`idSesion`, `Usuario_idUsuario`),
  INDEX `fk_Sesion_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Sesion_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Taxi`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
